title: üè† Home
description: Your complete DevOps study reference.
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: light

sass:
  style: compressed

just_the_docs:
  logo: "/assets/images/devops-logo.png"
  favicon_ico: "/assets/images/favicon.ico"
  search_enabled: true
  search_tokenizer_separator: /[\s/]+/
  heading_anchors: true
  last_edit_timestamp: false
  show_last_modified_time: false

  collections:
    devops:
      name: "DevOps Playbook"
      permalink: /:path/

  nav_sort: case_insensitive
  custom_css: custom/custom.scss

aux_links:
  üè† Home: https://natrajwadhai13.github.io/devops-playbook/
  GitHub Repo: https://github.com/natrajwadhai13/devops-playbook
  Portfolio: https://natrajwadhai13.github.io/devops-playbook/#portfolio
