title: üè† Home
description: Your complete DevOps study reference.
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: light

sass:
  style: compressed

just_the_docs:
  logo: "/assets/images/devops-logo.png"
  favicon_ico: "/assets/images/favicon.ico"
  search_enabled: true
  search_tokenizer_separator: /[\s/]+/
  heading_anchors: true
  last_edit_timestamp: false
  show_last_modified_time: false

  collections:
    devops:
      name: "DevOps Playbook"
      permalink: /:path/

  nav_sort: case_insensitive
  custom_css: custom/custom.scss

aux_links:
  üè† Home: https://natrajwadhai13.github.io/devops-playbook/
  GitHub Repo: https://github.com/natrajwadhai13/devops-playbook
  Portfolio: https://your-portfolio.com


<!-- _sidebar.md -->
- **Kubernetes**
  - [Overview](Kubernetes/Kubernetes.md)
  - [Basics](Kubernetes/Basics.md)
  - [Kubernetes Commands](Kubernetes/Kubernetes-Commands.md)
  - [Pods & Services](Kubernetes/Pods-Services.md)
  - [Storage](Kubernetes/Storage.md)
  - [Scheduling & Networking](Kubernetes/Scheduling-Networking.md)
  - [Security](Kubernetes/Security.md)
  - [Helm](Kubernetes/Helm.md)
  - [GitOps](Kubernetes/GitOps.md)
  - [Observability](Kubernetes/Observability.md)
  - [Autoscaling](Kubernetes/Autoscaling.md)
  - [Service Mesh](Kubernetes/Service-Mesh.md)

- **Hands-On**
  - [Kubernetes Commands](Hands-On/Kubernetes-Commands.md)
  - [YAML Practice](Hands-On/YAML-Practice.md)
  - [Minikube Setup](Hands-On/Minikube-Setup.md)
  - [Helm Practice](Hands-On/Helm-Practice.md)
  - [ArgoCD Setup](Hands-On/ArgoCD-Setup.md)

- **Interview**
  - [K8s Interview Questions](Interview/K8s-Interview-Questions.md)
  - [Helm Interview](Interview/Helm-Interview.md)
  - [DevOps + K8s Integration](Interview/DevOps-K8s-Integration.md)
  - [Real-Time Scenarios](Interview/Real-Time-Scenarios.md)

- **Advanced**
  - [Architecture Deep Dive](Advanced/Kubernetes-Architecture-DeepDive.md)
  - [Operators & CRDs](Advanced/Operators-and-CRD.md)
  - [Multi-Cluster Setup](Advanced/Multi-Cluster-Setup.md)
  - [Advanced Security](Advanced/Kubernetes-Security-Advanced.md)
  - [Troubleshooting](Advanced/K8s-Troubleshooting.md)

- **Summary**
  - [Kubernetes Overview](Summary/Kubernetes-Overview.md)
  - [Quick Revision](Summary/Kubernetes-Quick-Revision.md)
  - [Notes](Summary/Kubernetes-Notes.md)
